// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MLModel1_ConsoleApp3
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"Marital status")]
            public float Marital_status { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"Application mode")]
            public float Application_mode { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Application order")]
            public float Application_order { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Course")]
            public float Course { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Daytime/evening attendance")]
            public float Daytime_evening_attendance { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"Previous qualification")]
            public float Previous_qualification { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"Nacionality")]
            public float Nacionality { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"Mother's qualification")]
            public float Mother_s_qualification { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"Father's qualification")]
            public float Father_s_qualification { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"Mother's occupation")]
            public float Mother_s_occupation { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"Father's occupation")]
            public float Father_s_occupation { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"Displaced")]
            public float Displaced { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"Educational special needs")]
            public float Educational_special_needs { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"Debtor")]
            public float Debtor { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"Tuition fees up to date")]
            public float Tuition_fees_up_to_date { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"Gender")]
            public float Gender { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"Scholarship holder")]
            public float Scholarship_holder { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"Age at enrollment")]
            public float Age_at_enrollment { get; set; }

            [LoadColumn(18)]
            [ColumnName(@"International")]
            public float International { get; set; }

            [LoadColumn(19)]
            [ColumnName(@"Curricular units 1st sem (credited)")]
            public float Curricular_units_1st_sem__credited_ { get; set; }

            [LoadColumn(20)]
            [ColumnName(@"Curricular units 1st sem (1)")]
            public float Curricular_units_1st_sem__1_ { get; set; }

            [LoadColumn(21)]
            [ColumnName(@"Curricular units 1st sem (evaluations)")]
            public float Curricular_units_1st_sem__evaluations_ { get; set; }

            [LoadColumn(22)]
            [ColumnName(@"Curricular units 1st sem (approved)")]
            public float Curricular_units_1st_sem__approved_ { get; set; }

            [LoadColumn(23)]
            [ColumnName(@"Curricular units 1st sem (grade)")]
            public float Curricular_units_1st_sem__grade_ { get; set; }

            [LoadColumn(24)]
            [ColumnName(@"Curricular units 1st sem (without evaluations)")]
            public float Curricular_units_1st_sem__without_evaluations_ { get; set; }

            [LoadColumn(25)]
            [ColumnName(@"Curricular units 2nd sem (credited)")]
            public float Curricular_units_2nd_sem__credited_ { get; set; }

            [LoadColumn(26)]
            [ColumnName(@"Curricular units 2nd sem (1)")]
            public float Curricular_units_2nd_sem__1_ { get; set; }

            [LoadColumn(27)]
            [ColumnName(@"Curricular units 2nd sem (evaluations)")]
            public float Curricular_units_2nd_sem__evaluations_ { get; set; }

            [LoadColumn(28)]
            [ColumnName(@"Curricular units 2nd sem (approved)")]
            public float Curricular_units_2nd_sem__approved_ { get; set; }

            [LoadColumn(29)]
            [ColumnName(@"Curricular units 2nd sem (grade)")]
            public float Curricular_units_2nd_sem__grade_ { get; set; }

            [LoadColumn(30)]
            [ColumnName(@"Curricular units 2nd sem (without evaluations)")]
            public float Curricular_units_2nd_sem__without_evaluations_ { get; set; }

            [LoadColumn(31)]
            [ColumnName(@"Unemployment rate")]
            public float Unemployment_rate { get; set; }

            [LoadColumn(32)]
            [ColumnName(@"Inflation rate")]
            public float Inflation_rate { get; set; }

            [LoadColumn(33)]
            [ColumnName(@"GDP")]
            public float GDP { get; set; }

            [LoadColumn(34)]
            [ColumnName(@"Target")]
            public float Target { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Marital status")]
            public float Marital_status { get; set; }

            [ColumnName(@"Application mode")]
            public float Application_mode { get; set; }

            [ColumnName(@"Application order")]
            public float Application_order { get; set; }

            [ColumnName(@"Course")]
            public float Course { get; set; }

            [ColumnName(@"Daytime/evening attendance")]
            public float Daytime_evening_attendance { get; set; }

            [ColumnName(@"Previous qualification")]
            public float Previous_qualification { get; set; }

            [ColumnName(@"Nacionality")]
            public float Nacionality { get; set; }

            [ColumnName(@"Mother's qualification")]
            public float Mother_s_qualification { get; set; }

            [ColumnName(@"Father's qualification")]
            public float Father_s_qualification { get; set; }

            [ColumnName(@"Mother's occupation")]
            public float Mother_s_occupation { get; set; }

            [ColumnName(@"Father's occupation")]
            public float Father_s_occupation { get; set; }

            [ColumnName(@"Displaced")]
            public float Displaced { get; set; }

            [ColumnName(@"Educational special needs")]
            public float Educational_special_needs { get; set; }

            [ColumnName(@"Debtor")]
            public float Debtor { get; set; }

            [ColumnName(@"Tuition fees up to date")]
            public float Tuition_fees_up_to_date { get; set; }

            [ColumnName(@"Gender")]
            public float Gender { get; set; }

            [ColumnName(@"Scholarship holder")]
            public float Scholarship_holder { get; set; }

            [ColumnName(@"Age at enrollment")]
            public float Age_at_enrollment { get; set; }

            [ColumnName(@"International")]
            public float International { get; set; }

            [ColumnName(@"Curricular units 1st sem (credited)")]
            public float Curricular_units_1st_sem__credited_ { get; set; }

            [ColumnName(@"Curricular units 1st sem (1)")]
            public float Curricular_units_1st_sem__1_ { get; set; }

            [ColumnName(@"Curricular units 1st sem (evaluations)")]
            public float Curricular_units_1st_sem__evaluations_ { get; set; }

            [ColumnName(@"Curricular units 1st sem (approved)")]
            public float Curricular_units_1st_sem__approved_ { get; set; }

            [ColumnName(@"Curricular units 1st sem (grade)")]
            public float Curricular_units_1st_sem__grade_ { get; set; }

            [ColumnName(@"Curricular units 1st sem (without evaluations)")]
            public float Curricular_units_1st_sem__without_evaluations_ { get; set; }

            [ColumnName(@"Curricular units 2nd sem (credited)")]
            public float Curricular_units_2nd_sem__credited_ { get; set; }

            [ColumnName(@"Curricular units 2nd sem (1)")]
            public float Curricular_units_2nd_sem__1_ { get; set; }

            [ColumnName(@"Curricular units 2nd sem (evaluations)")]
            public float Curricular_units_2nd_sem__evaluations_ { get; set; }

            [ColumnName(@"Curricular units 2nd sem (approved)")]
            public float Curricular_units_2nd_sem__approved_ { get; set; }

            [ColumnName(@"Curricular units 2nd sem (grade)")]
            public float Curricular_units_2nd_sem__grade_ { get; set; }

            [ColumnName(@"Curricular units 2nd sem (without evaluations)")]
            public float Curricular_units_2nd_sem__without_evaluations_ { get; set; }

            [ColumnName(@"Unemployment rate")]
            public float Unemployment_rate { get; set; }

            [ColumnName(@"Inflation rate")]
            public float Inflation_rate { get; set; }

            [ColumnName(@"GDP")]
            public float GDP { get; set; }

            [ColumnName(@"Target")]
            public float Target { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel1.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
